name: extended_math
description: Library that add functionality of all maths sections that don't exist in dart:math.
version: 0.0.32+1
homepage: https://github.com/YevhenKap/extended_math
license: MIT

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  quiver: ^3.0.1

dev_dependencies:
  test: ^1.5.3
  pedantic: ^1.9.0
